//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// VIEWER.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VIEWER_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_LOADING              130
#define IDD_DIALOG_MAIN                 132
#define IDD_DIALOG_ABILITY              134
#define IDB_BITMAP_BG                   136
#define IDB_BITMAP_LOGO                 137
#define IDB_BITMAP_PAUSE                138
#define IDB_BITMAP_PAUSE_ALL            139
#define IDB_BITMAP_START                140
#define IDB_BITMAP_START_ALL            141
#define IDB_BITMAP_SAVE_ALL             142
#define IDD_DIALOG_FOCUS_1              146
#define IDD_DIALOG_FOCUS_2              147
#define IDD_DIALOG_FOCUS_3              148
#define IDD_DIALOG_FOCUS_4              149
#define IDD_DIALOG_FOCUS_5              150
#define IDB_BITMAP_OFF                  150
#define IDB_BITMAP_ON                   151
#define IDB_BITMAP_SAVE                 152
#define IDI_ICON1                       153
#define IDI_ICON_LOGO                   153
#define IDI_ICON_WIA                    153
#define IDB_BITMAP_OFF_WHITE            154
#define IDB_BITMAP_ON_WHITE             155
#define IDB_BITMAP_SAVE_WHITE           156
#define IDB_BITMAP_ANGLE_OFF            157
#define IDB_BITMAP_ANGLE_ON             158
#define IDB_BITMAP_CIRCLE_OFF           159
#define IDB_BITMAP_CIRCLE_ON            160
#define IDB_BITMAP_DISTANCE_OFF         161
#define IDB_BITMAP_DISTANCE_ON          162
#define IDB_BITMAP_GRAPHIC_OFF          163
#define IDB_BITMAP_GRAPHIC_ON           164
#define IDB_BITMAP_LINE_OFF             165
#define IDB_BITMAP_LINE_ON              166
#define IDB_BITMAP_RECTANGLE_OFF        167
#define IDB_BITMAP_RECTANGLE_ON         168
#define IDB_BITMAP_DELETE               169
#define IDB_BITMAP_FOLDER               170
#define IDB_BITMAP_SAVE_LOG             171
#define IDD_DIALOG_SAVE_ALARM           172
#define IDC_PIC_BG                      1001
#define IDC_STATIC_DAY                  1002
#define IDC_STATIC_TIME                 1003
#define IDC_PIC_LOGO                    1004
#define IDC_PIC_LEFT                    1005
#define IDC_PIC_BOTTOM                  1006
#define IDC_STATIC_TITLE                1007
#define IDC_BTN_CAM_1_ACTIVE            1008
#define IDC_BTN_CAM_ACTIVE_ALL          1009
#define IDC_BTN_CAMERA_SET              1009
#define IDC_BTN_MEASURE                 1010
#define IDC_BTN_CAM_SAVE_ALL            1011
#define IDC_BTN_HISTORY                 1011
#define IDC_BTN_CAM_2_ACTIVE            1012
#define IDC_BTN_RECORDER                1012
#define IDC_BTN_CAM_3_ACTIVE            1013
#define IDC_BTN_LOG                     1013
#define IDC_BTN_CAM_4_ACTIVE            1014
#define IDC_CMB_CAMERA_EXPOSURE         1014
#define IDC_BTN_CAM_5_ACTIVE            1015
#define IDC_SLIDER_EXPOSURE             1015
#define IDC_STATIC_CAM_1                1016
#define IDC_STATIC_CAM_2                1017
#define IDC_STATIC_CAM_3                1018
#define IDC_STATIC_CAM_4                1019
#define IDC_STATIC_CAM_5                1020
#define IDC_EDIT_EXPOSURE               1021
#define IDC_STATIC_CAM_ALL              1021
#define IDC_STATIC_CAM_1_EXPOSURE       1022
#define IDC_STATIC_CAM_SAVE             1022
#define IDC_STATIC_CAM_2_EXPOSURE       1023
#define IDC_STATIC_CAM_3_EXPOSURE       1024
#define IDC_STATIC_CAM_4_EXPOSURE       1025
#define IDC_STATIC_CAM_5_EXPOSURE       1026
#define IDC_BTN_EDIT                    1027
#define IDC_GRP_EXPOSURE                1029
#define IDC_GRP_EDIT                    1030
#define IDC_BTN_GRAPHIC                 1040
#define IDC_BTN_RECTANGLE               1045
#define IDC_BTN_CIRCLE                  1046
#define IDC_BTN_LINE                    1047
#define IDC_BTN_DISTANCE                1048
#define IDC_BTN_ANGLE                   1049
#define IDC_LIST_MEASURE                1050
#define IDC_GRP_MEASURE                 1051
#define IDC_SHELLTREE_HISTORY           1052
#define IDC_PIC_HISTORY                 1053
#define IDC_LIST_HISTORY                1054
#define IDC_GRP_HISTORY                 1055
#define IDC_PIC_EDIT                    1056
#define IDC_GRP_LOG                     1057
#define IDC_LIST_LOG                    1058
#define IDC_BTN_SAVE_LOG                1059
#define IDC_BTN_DELETE_LOG              1060
#define IDC_EDIT_PATH                   1061
#define IDC_BTN_PATH                    1062
#define IDC_PROGRESS_PATH               1063
#define IDC_BTN_PATH_SET                1064
#define IDC_STATIC_PATH                 1065
#define IDC_PIC_CAM_1                   1066
#define IDC_BTN_DELETE                  1066
#define IDC_PIC_CAM_2                   1067
#define IDC_CMB_FOCUS_WINDOW            1067
#define IDC_BTN_DELETE_ALL              1067
#define IDC_PIC_CAM_3                   1068
#define IDC_STATIC_FOCUS_WINDOW         1068
#define IDC_PIC_CAM_4                   1069
#define IDC_LIST_EDIT                   1069
#define IDC_STATIC_FOCUS_1              1069
#define IDC_PIC_CAM_5                   1070
#define IDC_CMB_FOCUS_1                 1070
#define IDC_STATIC_FOCUS_2              1071
#define IDC_STATIC_FOCUS_3              1072
#define IDC_STATIC_FOCUS_4              1073
#define IDC_STATIC_FOCUS_5              1074
#define IDC_CMB_FOCUS_2                 1075
#define IDC_CMB_FOCUS_3                 1076
#define IDC_CMB_FOCUS_4                 1077
#define IDC_CMB_FOCUS_5                 1078
#define IDC_STATIC_X                    1079
#define IDC_STATIC_Y                    1080
#define IDC_BTN_EDIT_SET                1080
#define IDC_STATIC_VALUE_1              1081
#define IDC_STATIC_VALUE_2              1082
#define IDC_STATIC_FOCUS                1084
#define IDC_STATIC_X_POS                1085
#define IDC_PIC_CAM                     1085
#define IDC_STATIC_Y_POS                1086
#define IDC_STATIC_MODE                 1087
#define IDC_STATIC_CASE_1               1088
#define IDC_STATIC_CASE_2               1089
#define IDC_BTN_SETTING                 1090
#define IDC_EDIT_TEST                   1091
#define IDC_STATIC_MAGNI                1093
#define IDC_PIC_LOADING                 1094
#define IDC_STATIC_ALARM                1095

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1096
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
